# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###
GET http://127.0.0.1:8000/mail/test?email=3493598861@qq.com

###
GET http://127.0.0.1:8000/auth/code?email=3493598861@qq.com


###
POST http://127.0.0.1:8000/auth/register
Content-Type: application/json

{
  "email": "3493598861@qq.com",
  "username": "hynever",
  "password": "123456",
  "confirm_password": "123456",
  "code":"3080"

}
###
POST http://127.0.0.1:8000/auth/login
Content-Type: application/json

{
  "email": "3493598861@qq.com",
  "password": "123456"
}

###
POST http://127.0.0.1:8000/name
Content-Type: application/json

{
  "surname": "王",
  "length": "两字",
  "gender": "男",
  "other": "大气"
}